Increased frequency of apy updates
novasamatech/subquery-staking pull request #20
Opened 2023-06-30 09:26 UTC by vovunku

Changed new era handlers on NewSession for relaychain and azero

Checked from 18579664 to observe two apy updates:

First:
![Screenshot from 2023-06-30 10-35-43](https://github.com/novasamatech/subquery-staking/assets/33938211/ca20578c-e239-42af-ad29-68feeba17376)

Second:
![Screenshot from 2023-06-30 10-37-17](https://github.com/novasamatech/subquery-staking/assets/33938211/a3b7bad0-36f8-4935-900b-40a3652860b6)

Renaming of handlers haven't done yet. as for parachains logic remains the same.

2023-07-02 16:57 UTC, ERussel requested changes
As we discussed:

1) Make sure we only recalculate APY each session and cache's validator on StakersElected
2) Make sure that we also recalculate APY when new stakers elected

2023-07-03 21:35 UTC, vovunku commented
1. fixed with separating by two handlers
2. fixed by updating apy on new era also

Should bee good now.

> As we discussed:
> 
> 1. Make sure we only recalculate APY each session and cache's validator on StakersElected
> 2. Make sure that we also recalculate APY when new stakers elected

2023-07-05 10:30 UTC, ERussel commented on src/mappings/kusama.ts
> +    let validatorEraInfoDataSource = new ValidatorEraInfoDataSource();
As we are recreating datasource on each session that means also we are fetching validators each session. This is time-consuming operation. Better fetch validators once in era and then cache.

2023-07-07 15:59 UTC, vovunku commented
Similar testes:

From zero:

![Screenshot from 2023-07-07 17-46-46](https://github.com/novasamatech/subquery-staking/assets/33938211/72bef405-ec66-4770-a32d-5055e6824a01)

Logs:
[all_from_1.log](https://github.com/novasamatech/subquery-staking/files/11983872/all_from_1.log)

Note: as we made broken logic for relaychains on first blocks **I saw 1500. APY on polkadot relaychain**(but forgot made screenshot)

From 18685151 kusama:

Before:
![Screenshot from 2023-07-07 17-54-45](https://github.com/novasamatech/subquery-staking/assets/33938211/d296544d-cbd2-402c-a20d-dbcc3947d568)
After:
![Screenshot from 2023-07-07 17-55-32](https://github.com/novasamatech/subquery-staking/assets/33938211/83cf5135-eb46-4bf6-8894-4bd3b4556be5)

Logs:

[kusama_from_18685151.log](https://github.com/novasamatech/subquery-staking/files/11983894/kusama_from_18685151.log)

2023-07-11 07:51 UTC, vovunku commented
![Screenshot from 2023-07-11 09-49-19](https://github.com/novasamatech/subquery-staking/assets/33938211/85ba0a27-ad16-43d8-8f52-31a34eacde2e)

[tmp.log](https://github.com/novasamatech/subquery-staking/files/12012108/tmp.log)


I can make more tests, if it is necessary!

2023-07-11 08:02 UTC, vovunku commented
Similar test for kusama session update
First session:
![Screenshot from 2023-07-11 09-59-21](https://github.com/novasamatech/subquery-staking/assets/33938211/9849f17c-98bd-497f-a194-507e87a53b77)


Second session:
![Screenshot from 2023-07-11 10-00-14](https://github.com/novasamatech/subquery-staking/assets/33938211/b648a335-6c9c-4f05-8ddc-66f4205d344c)

Log:
[tmp.log](https://github.com/novasamatech/subquery-staking/files/12012204/tmp.log)

2023-07-12 11:35 UTC, ERussel approved these changes

2023-07-12 11:35 UTC, merged