new EraStakers interface support
novasamatech/subquery-staking pull request #41
Opened 2023-12-27 09:53 UTC by vovunku

2023-12-28 08:04 UTC, vovunku commented
![Screenshot from 2023-12-28 08-56-44](https://github.com/novasamatech/subquery-staking/assets/33938211/58124ab3-eb5b-4cf9-9465-9fc8ac9a89e1)
![Screenshot from 2023-12-28 09-02-27](https://github.com/novasamatech/subquery-staking/assets/33938211/2e5b1778-3baa-408b-9067-560ac9071bd2)
![Screenshot from 2023-12-28 09-02-19](https://github.com/novasamatech/subquery-staking/assets/33938211/0dbfc796-3381-4127-b02c-19a42d5e41df)
![Screenshot from 2023-12-27 10-46-09](https://github.com/novasamatech/subquery-staking/assets/33938211/4d42d72e-e937-45f3-b6fe-dd503a0770aa)

2023-12-28 08:14 UTC, valentunn requested changes

2023-12-28 08:14 UTC, valentunn commented on src/mappings/era/ValidatorEraInfoDataSource.ts
> +        }, {})
This does not guarantee that pages will be ordered. I better suggest to use approach similar to what we use in the client code

![image](https://github.com/novasamatech/subquery-staking/assets/70131744/808d4275-8c3b-4c5b-9fb7-64d4c3eb81d4)

2023-12-28 10:42 UTC, vovunku commented
![Uploading Screenshot from 2023-12-28 11-40-17.png…]()

2023-12-28 10:42 UTC, vovunku commented
![Screenshot from 2023-12-28 11-40-17](https://github.com/novasamatech/subquery-staking/assets/33938211/3f7263d2-60ee-4635-927b-d098669ed77f)

2023-12-28 10:49 UTC, valentunn approved these changes

2024-01-17 12:07 UTC, ERussel approved these changes

2024-01-17 12:07 UTC, merged